name: mypkfitapptest

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  appTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
  

      # Runs a set of commands using the runners shell
      - name: checkout appium 
        run: |
          git clone https://github.com/browserstack/python-appium-app-browserstack
          cp apptest.py python-appium-app-browserstack
          ls python-appium-app-browserstack
      - name: Start BrowserStack mypkfit App Test
        run: python python-appium-app-browserstack/apptest.py
